version: "3"
services: 
  rtmp:
    build: ./rtmp
    ports: 
      - "1935:1935"
    container_name: rtmp_server
    volumes: 
      - ./data:/tmp/hls
  auth:
    build: ./auth
    container_name: auth_server
    